### ISSUE TITLE
Allow developer to directly specify game version

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/teak-unity#28]
We've seen, repeatedly, games just completely mess up their OS version information. They get long and short version confused, they add _prefixes_ instead of _postfixes_ to separate architecture, so versions don't consistently increase, they just... add random stuff to version number because at one point someone screwed up versions and the only option was to screw them up even more to ship the build.

This creates a lot of confusion for our users because marketing works with the 'marketing' version, which may not be reflected by what the devs have specified in the standard system version information _at all_. However, we do know that all games have consistently gotten the correct marketing version in their settings page, implying that given the power to do so devs can set a consistent version number. I think the key requirement is simply... that there's no other job to be done besides 'this is the marketing version number'.

As such, we should provide a way for developers to directly specify the game version. I don't know if this is a new res/values / Info.plist setting, or a provided API that must be called before IdentifyUser(). Use of this should be optional -- we'll always still report the official versions back to the server. But, if this value is present, it should also be sent.

**Comment by ZeroStride** [comment]
Can now be specified via remote configuration as `dynamic_parameters`, example:

`{
    "app_version_developer" : {
      "android" : "io_teak_developer_version",
      "ios" : "TeakDeveloperVersion"
    }
  }`

This is the default built in to the SDK, a remote configuration can override this.
