### ISSUE TITLE
Make link anchors in changelog permanent

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/teak-unity#47]
Currently the anchor links for the changelog in the docs are e.g. #id1, #id2, etc. The problem with this is that when we add a new entry this changes all of the anchors -- #id1 _always_ points to the most recent changelog entry.

For various reasons, it would be quite nice to have permanent links to specific changelog entries.

**Comment by ZeroStride** [comment]
After a look, it seems like what's happening is that it's `#id1` etc because I'm using the `.. include` directive in the changelog instead of just slamming all the files together.

If we slam the files together that should resolve it automatically.

**Comment by ZeroStride** [comment]
Nope it was way more complicated.

**Comment by ZeroStride** [comment]
The first two anchor links for iOS/Android subheadings always links to #android and #ios, even though it will also link to #android-version.

Not sure how to resolve this.

**Comment by AlexSc** [comment]
Unfortunately the fix for #51 regressed this

**Comment by ZeroStride** [comment]
Fixing in new docs
