### ISSUE TITLE
InternalOnCallbackError should provide stack trace for source exception

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/teak-unity#65]
[InternalOnCallbackError](https://github.com/GoCarrot/teak-unity/blob/e940e7961aa188ea3f80c6875c606b247046858e/Assets/Teak/Teak.cs#L851) uses Debug.LogError, which provides the stack trace of _calling_ InternalOnCallbackError, and then only logs exception.ToString(). This results in the only stack trace showing up in logs being the stack trace for calling InteranalOnCallbackError, and obfuscates the stack trace for the source exception.

InternalOnCallbackError should log the stack trace of the source exception to facilitate debugging of callback issues.

**Comment by ZeroStride** [comment]
This was found to already be the case, and the error that they were getting was because the callback provided to `SafePerformCallback` was `null`. The resolution was to do a null check before executing `callback`.
